Repository discordjs/guide, pull requests merged in 2018-08, with the labels that each got.

#119 Add a page on notation
  guide/_sidebar.md
  guide/additional-info/notation.md
  guide/assets/img/search.png
  guide/assets/img/send.png
  guide/popular-topics/common-questions.md
Labels: page/section addition

#126 Discord message component
  .eslintignore
  CONTRIBUTING.md
  TODO.md
  guide/assets/css/dark.css
  guide/assets/css/main.css
  guide/assets/img/discord-avatar-blue.png
  guide/assets/img/discord-avatar-djs.png
  guide/assets/img/discord-avatar-green.png
  guide/assets/js/init.js
  guide/assets/js/main.js
  guide/assets/js/vue.min.js
  guide/index.html
Labels: enhancement

#129 Feat: own popular topic for Embeds
  guide/_sidebar.md
  guide/popular-topics/embeds.md
  guide/popular-topics/miscellaneous-examples.md
Labels: page/section addition

#130 fix: sharding not obtaining guild correctly
  code-samples/sharding/extended/bot.js
  guide/sharding/extended.md
Labels: bug fix

#125 Add OAuth2 Page
  code-samples/oauth/simple-oauth-webserver/index.html
  code-samples/oauth/simple-oauth-webserver/index.js
  guide/_sidebar.md
  guide/assets/img/18e2dwi.png
  guide/assets/img/1ch98sm.png
  guide/assets/img/49jali8.png
  guide/assets/img/9fejia2.png
  guide/oauth2/README.md
Labels: page/section addition
