Repository discordjs/guide, pull requests merged in 2018-02, with the labels that each got.

#79 Add mention prefix example
  guide/popular-topics/miscellaneous-examples.md
Labels: page/section addition

#76 Add linting support for JS files and JS codeblocks in .md files
  .eslintrc.json
  .gitignore
  TODO.md
  guide/.eslintrc.json
  guide/additional-info/async-await.md
  guide/additional-info/es6-syntax.md
  guide/assets/js/.eslintrc.json
  guide/assets/js/dark-theme.js
  guide/assets/js/main.js
  guide/command-handling/adding-features.md
  guide/creating-your-bot/adding-more-commands.md
  guide/creating-your-bot/commands-with-user-input.md
  guide/popular-topics/collectors.md
  guide/popular-topics/common-questions.md
  guide/popular-topics/reactions.md
  guide/sequelize/README.md
  guide/sequelize/currency.md
  guide/sharding/additional-information.md
  package-lock.json
  package.json
Labels: code refactoring, enhancement

#81 Add REST API Tutorial
  code_samples/additional-info/rest-api/index.js
  guide/_sidebar.md
  guide/additional-info/rest-api.md
  guide/assets/img/N0t4M.png
  guide/assets/img/RMv88.png
Labels: page/section addition

#84 Update initial command handler page for clarity
  guide/command-handling/README.md
Labels: enhancement, page/section addition

#83 Add general guidelines to the contributing.md file
  CONTRIBUTING.md
  TODO.md
Labels: enhancement
