Repository discordjs/guide, pull requests merged in 2019-11, with the labels that each got.

#281 Add guide on reloading commands
  code-samples/command-handling/adding-features/11/commands/reload.js
  code-samples/command-handling/adding-features/12/commands/reload.js
  guide/command-handling/adding-features.md
Labels: type: page/section addition

#283 Destructure the d.js lib
  guide/additional-info/rest-api.md
Labels: meta: branching, type: enhancement

#284 Node version corrected with inline branch
  guide/preparations/README.md
Labels: meta: branching, type: enhancement

#291 Use play instead of playStream for master branch code
  guide/popular-topics/miscellaneous-examples.md
Labels: meta: branching, type: bug fix

#293 Update canvas.md
  guide/popular-topics/canvas.md
Labels: type: bug fix

#282 Add issue templates
  .github/ISSUE_TEMPLATE/branching-content.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/typo_fix.md
Labels: type: enhancement

#285 Style changes
  guide/preparations/setting-up-a-linter.md
Labels: type: spelling/grammar
