Repository discordjs/guide, pull requests merged in 2019-06, with the labels that each got.

#218 Add branch version selector dropdown to user settings
  CONTRIBUTING.md
  guide/.vuepress/branches.js
  guide/.vuepress/components/Branch.vue
  guide/.vuepress/components/BranchSelector.vue
  guide/.vuepress/config.js
  guide/.vuepress/eventBus.js
  package.json
  yarn.lock
Labels: enhancement

#228 Corrected Link
  guide/improving-dev-environment/pm2.md
Labels: bug fix

#222 Partials
  code-samples/popular-topics/reactions/raw-event.js
  code-samples/popular-topics/reactions/uncached-messages.js
  guide/.vuepress/sidebar.js
  guide/popular-topics/partials.md
  guide/popular-topics/reactions.md
Labels: page/section addition

#238 Update args.md
  guide/commando/args.md
Labels: spelling/grammar
