Repository discordjs/guide, pull requests merged in 2019-10, with the labels that each got.

#263 Update creating bot steps
  guide/preparations/setting-up-a-bot-application.md
Labels: enhancement

#265 Adding two examples
  guide/popular-topics/common-questions.md
Labels: enhancement

#268 Frontport examples to V12-changes
  guide/popular-topics/common-questions.md
Labels: page/section addition

#264 Slight rework of the grammar/text in the sequelize guide
  guide/sequelize/README.md
Labels: spelling/grammar

#269 Update useful-packages.md
  guide/miscellaneous/useful-packages.md
Labels: bug fix

#272 Change from _sidebar.md to sidebar.js
  CONTRIBUTING.md
Labels: bug fix

#274 Upgrade core VuePress, theme, and relevant plugins
  guide/.vuepress/config.js
  guide/.vuepress/enhanceApp.js
  guide/.vuepress/style.styl
  package.json
  yarn.lock
Labels: code refactoring, enhancement

#275 Improve branch selector UI/UX
  guide/.vuepress/branches.js
  guide/.vuepress/components/BranchSelector.vue
  guide/.vuepress/config.js
  guide/.vuepress/styles/index.styl
Labels: code refactoring, enhancement

#278 Enhance `configuration-files` example to utilize the configurized prefix.
  code-samples/creating-your-bot/configuration-files/index.js
Labels: enhancement

#279 Revert "Enhance `configuration-files` example to utilize the configurized prefix."
  code-samples/creating-your-bot/configuration-files/index.js
Labels: bug fix

#276 Make most links to docs branch relative; small fixes around branch specific content
  guide/command-handling/README.md
  guide/command-handling/adding-features.md
  guide/commando/permissions.md
  guide/creating-your-bot/adding-more-commands.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/popular-topics/collectors.md
  guide/popular-topics/embeds.md
  guide/popular-topics/partials.md
  guide/popular-topics/permissions.md
  guide/popular-topics/reactions.md
  guide/preparations/README.md
  guide/sharding/README.md
  guide/sharding/additional-information.md
Labels: bug fix, code refactoring, enhancement
