Repository discordjs/guide, pull requests merged in 2020-09, with the labels that each got.

#476 fix: use console.error when logging errors
  code-samples/command-handling/adding-features/11/commands/reload.js
  code-samples/command-handling/adding-features/12/commands/reload.js
  code-samples/popular-topics/reactions/12/uncached-messages.js
  guide/command-handling/adding-features.md
  guide/miscellaneous/useful-packages.md
  guide/popular-topics/reactions.md
Labels: type: enhancement

#478 fix(embeds): remove outdated embed note
  guide/popular-topics/audit-logs.md
  guide/popular-topics/embeds.md
Labels: reason: Discord changes, type: enhancement

#480 fix(v12-changes): fix ‘Dynamic File type’ heading
  guide/additional-info/changes-in-v12.md
Labels: type: typo
