Repository discordjs/guide, pull requests merged in 2020-10, with the labels that each got.

#470 add section about converting Permissions into flags
  guide/popular-topics/permissions.md
Labels: t: page/section addition, type: enhancement

#486 Update additional-information.md
  guide/sharding/additional-information.md
Labels: type: typo

#488 chore: switch domain from discordapp.com to discord.com
  code-samples/oauth/simple-oauth-webserver/index.html
  code-samples/oauth/simple-oauth-webserver/index.js
  guide/oauth2/README.md
  guide/popular-topics/audit-logs.md
  guide/popular-topics/embeds.md
  guide/popular-topics/errors.md
  guide/popular-topics/intents.md
  guide/popular-topics/permissions-extended.md
  guide/popular-topics/permissions.md
  guide/popular-topics/webhooks.md
  guide/preparations/setting-up-a-bot-application.md
  guide/sharding/README.md
  guide/voice/receiving-audio.md
  package.json
Labels: reason: Discord changes, type: enhancement

#495 fix: Tips regarding Intents
  guide/popular-topics/intents.md
Labels: type: enhancement

#499 fix(*): various typos
  guide/additional-info/async-await.md
  guide/additional-info/changes-in-v12.md
  guide/additional-info/es6-syntax.md
  guide/additional-info/rest-api.md
  guide/commando/README.md
  guide/creating-your-bot/commands-with-user-input.md
  guide/improving-dev-environment/package-json-scripts.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/oauth2/README.md
  guide/popular-topics/collectors.md
  guide/popular-topics/errors.md
  guide/popular-topics/partials.md
  guide/popular-topics/reactions.md
  guide/preparations/adding-your-bot-to-servers.md
  guide/preparations/setting-up-a-bot-application.md
  guide/sequelize/currency.md
  guide/sharding/README.md
  guide/sharding/extended.md
  guide/voice/optimisation-and-troubleshooting.md
  guide/voice/understanding-voice.md
  guide/voice/voice-broadcasts.md
Labels: type: enhancement, type: typo

#500 feat: improve accuracy on toString changes
  guide/additional-info/changes-in-v12.md
Labels: type: enhancement

#508 fix(changes-in-v12): typo
  guide/additional-info/changes-in-v12.md
Labels: type: typo

#503 fix(permissions): 404 caused by typo in docs URL
  guide/popular-topics/permissions.md
Labels: type: bugfix

#509 feat: Add Netlify badge to intro page
  CODE_OF_CONDUCT.md
  guide/README.md
Labels: type: enhancement

#501 feat: merge common-questions and misc into faq
  guide/.vuepress/sidebar.js
  guide/additional-info/rest-api.md
  guide/popular-topics/faq.md
  guide/popular-topics/miscellaneous-examples.md
  guide/requesting-more-content.md
Labels: type: enhancement

#507 feat(parsing-mentions): add second command that showcases multiple mentions
  code-samples/miscellaneous/parsing-mention-arguments/11/index.js
  code-samples/miscellaneous/parsing-mention-arguments/12/index.js
  guide/miscellaneous/parsing-mention-arguments.md
Labels: type: enhancement

#511 fix(*): Various typos and consistency changes
  CONTRIBUTING.md
  code-samples/commando/getting-started/index.js
  code-samples/sharding/extended/11/bot.js
  code-samples/sharding/extended/12/bot.js
  code-samples/sharding/getting-started/11/bot.js
  code-samples/sharding/getting-started/12/bot.js
  guide/additional-info/es6-syntax.md
  guide/additional-info/rest-api.md
  guide/commando/README.md
  guide/creating-your-bot/commands-with-user-input.md
  guide/improving-dev-environment/package-json-scripts.md
  guide/miscellaneous/useful-packages.md
  guide/popular-topics/embeds.md
  guide/popular-topics/errors.md
  guide/popular-topics/intents.md
  guide/popular-topics/permissions-extended.md
  guide/popular-topics/permissions.md
  guide/preparations/adding-your-bot-to-servers.md
  guide/preparations/setting-up-a-bot-application.md
  guide/sequelize/currency.md
  guide/sharding/README.md
  guide/sharding/additional-information.md
  guide/voice/receiving-audio.md
  guide/voice/understanding-voice.md
Labels: type: typo

#513 Remove Bastion example
  guide/sharding/additional-information.md
Labels: type: enhancement
