Repository discordjs/guide, pull requests merged in 2020-01, with the labels that each got.

#304 Add topic to reactions page about removing reactions
  guide/popular-topics/reactions.md
Labels: type: page/section addition

#305 Add webhook section
  code-samples/popular-topics/webhooks/11/using-Webhook.js
  code-samples/popular-topics/webhooks/11/using-WebhookClient.js
  code-samples/popular-topics/webhooks/12/using-Webhook.js
  code-samples/popular-topics/webhooks/12/using-WebhookClient.js
  guide/.vuepress/sidebar.js
  guide/images/creating-webhooks-1.png
  guide/images/creating-webhooks-2.png
  guide/popular-topics/webhooks.md
Labels: type: page/section addition

#309 Fix malformed branch tag
  guide/preparations/README.md
Labels: type: bug fix

#271 Add guide page for audit logs
  guide/.vuepress/sidebar.js
  guide/popular-topics/audit-logs.md
Labels: type: page/section addition

#311 chore: clean up github templates
  .github/ISSUE_TEMPLATE/branching-content.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/typo_fix.md
Labels: github

#306 Update Partials
  code-samples/popular-topics/reactions/12/uncached-messages.js
  guide/popular-topics/partials.md
  guide/popular-topics/reactions.md
Labels: branching, enhancement

#214 Create a voice guide for v12
  guide/.vuepress/sidebar.js
  guide/voice/README.md
  guide/voice/optimisation-and-troubleshooting.md
  guide/voice/receiving-audio.md
  guide/voice/the-basics.md
  guide/voice/understanding-voice.md
  guide/voice/voice-broadcasts.md
Labels: page/section addition

#317 feat: embed guide rewording + embed editing
  guide/popular-topics/embeds.md
Labels: enhancement, page/section addition

#316 feat(v12): dynamic urls
  code-samples/command-handling/adding-features/12/commands/avatar.js
  code-samples/command-handling/dynamic-commands/12/commands/avatar.js
  code-samples/command-handling/file-setup/12/commands/avatar.js
  code-samples/command-handling/file-setup/12/index.js
  code-samples/creating-your-bot/commands-with-user-input/12/index.js
  code-samples/miscellaneous/parsing-mention-arguments/12/index.js
  guide/additional-info/changes-in-v12.md
  guide/creating-your-bot/commands-with-user-input.md
Labels: branching, enhancement

#319 Docs links and method names fixes in webhooks part
  guide/popular-topics/webhooks.md
Labels: enhancement

#320 fix markdown
  guide/additional-info/changes-in-v12.md
Labels: spelling/grammar
