Repository discordjs/guide, pull requests merged in 2020-03, with the labels that each got.

#338 Update required node version to V12 & npm install command
  guide/additional-info/changes-in-v12.md
  guide/commando/README.md
  guide/preparations/README.md
Labels: enhancement

#335 destructure all properties in the sharding guide
  code-samples/sharding/getting-started/bot.js
  guide/sharding/README.md
Labels: enhancement

#342 typo: additional-info/async-await
  guide/additional-info/async-await.md
Labels: spelling/grammar

#346 Add missing updates to Client information
  guide/additional-info/changes-in-v12.md
Labels: enhancement

#341 Change default Discord.js version of guide to v12
  guide/.vuepress/branches.js
Labels: enhancement

#351 Fix error in partials guide
  guide/popular-topics/partials.md
Labels: bug fix

#344 Fix sharding example code and separate sharding code samples
  code-samples/sharding/extended/11/bot.js
  code-samples/sharding/extended/11/index.js
  code-samples/sharding/extended/12/bot.js
  code-samples/sharding/extended/12/index.js
  code-samples/sharding/getting-started/11/bot.js
  code-samples/sharding/getting-started/11/index.js
  code-samples/sharding/getting-started/12/bot.js
  code-samples/sharding/getting-started/12/index.js
  guide/sharding/extended.md
Labels: bug fix

#352 docs(readme): fix links to guide
  README.md
Labels: enhancement

#357 fix: for..of iteration in reactions guide
  guide/popular-topics/reactions.md
Labels: bug fix
