Repository discordjs/guide, pull requests merged in 2020-05, with the labels that each got.

#392 Update webhook-related content with v12 changes.
  guide/additional-info/changes-in-v12.md
  guide/popular-topics/webhooks.md
Labels: branching, bug fix

#395 chore: change label to v11.6 + point docs to v11 branch
  guide/.vuepress/branches.js
  guide/command-handling/README.md
  guide/command-handling/adding-features.md
  guide/commando/permissions.md
  guide/creating-your-bot/adding-more-commands.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/popular-topics/collectors.md
  guide/popular-topics/embeds.md
  guide/popular-topics/permissions.md
  guide/popular-topics/reactions.md
  guide/popular-topics/webhooks.md
  guide/sharding/README.md
  guide/sharding/additional-information.md
Labels: enhancement

#396 feat: Add d.js docs link component
  CONTRIBUTING.md
  guide/.vuepress/branches.js
  guide/.vuepress/components/Branch.vue
  guide/.vuepress/components/BranchSelector.vue
  guide/.vuepress/components/DocsLink.vue
  guide/.vuepress/mixins/branches.js
Labels: enhancement

#401 Make the emoji characters correct
  guide/popular-topics/miscellaneous-examples.md
Labels: enhancement

#408 fix: remove an extra word
  guide/keyv/README.md
Labels: spelling/grammar

#400 URL update
  guide/preparations/adding-your-bot-to-servers.md
Labels: enhancement

#393 Tweaks to Sharding guide
  guide/sharding/README.md
Labels: bug fix
