Repository discordjs/guide, pull requests merged in 2020-02, with the labels that each got.

#322 Change reactions page to use MessageReaction#remove
  guide/popular-topics/reactions.md
Labels: enhancement

#318 Refactor master code samples for upcoming master Manager changes
  code-samples/miscellaneous/parsing-mention-arguments/12/index.js
  code-samples/popular-topics/canvas/12/index.js
  code-samples/popular-topics/permissions/12/index.js
  guide/additional-info/changes-in-v12.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/popular-topics/canvas.md
  guide/popular-topics/common-questions.md
  guide/popular-topics/permissions.md
  guide/popular-topics/reactions.md
  guide/sharding/README.md
Labels: enhancement

#325 add more branch tags to support v12 code
  guide/additional-info/async-await.md
  guide/commando/README.md
  guide/popular-topics/common-questions.md
  guide/popular-topics/errors.md
  guide/popular-topics/permissions.md
  guide/sharding/README.md
  guide/sharding/extended.md
Labels: branching, enhancement

#330 fix wording
  guide/popular-topics/common-questions.md
Labels: bug fix

#332 Change addField to addFields for v12
  code-samples/additional-info/rest-api/12/index.js
  guide/additional-info/changes-in-v12.md
  guide/additional-info/rest-api.md
  guide/popular-topics/embeds.md
  guide/popular-topics/errors.md
Labels: branching, enhancement

#328 feat/fix: more branch tags + some typos
  guide/creating-your-bot/commands-with-user-input.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/popular-topics/canvas.md
  guide/popular-topics/common-questions.md
  guide/popular-topics/embeds.md
  guide/popular-topics/permissions.md
  guide/popular-topics/reactions.md
  guide/popular-topics/webhooks.md
  guide/sharding/README.md
  guide/sharding/additional-information.md
  guide/sharding/extended.md
Labels: branching, enhancement

#333 Fix/remove links in table of contents in v12-changes
  guide/additional-info/changes-in-v12.md
Labels: bug fix

#334 fix: Update Commando guide to v12
  guide/commando/args.md
  guide/commando/client-values.md
Labels: branching, enhancement

#337 Fix inline branch tags
  guide/miscellaneous/parsing-mention-arguments.md
  guide/popular-topics/permissions.md
  guide/popular-topics/reactions.md
  guide/sharding/README.md
  guide/sharding/extended.md
Labels: bug fix
