Repository discordjs/guide, pull requests merged in 2020-11, with the labels that each got.

#518 Update v11 -> v12 changes for client#shardResume
  guide/additional-info/changes-in-v12.md
Labels: type: bugfix

#516 Fix tiny typo
  guide/sequelize/README.md
Labels: type: typo

#515 Fixed a spelling mistake i found :)
  guide/miscellaneous/parsing-mention-arguments.md
Labels: type: typo

#514 Update bot.js
  code-samples/sharding/extended/12/bot.js
Labels: type: bugfix

#530 Grammar Fix
  guide/additional-info/changes-in-v12.md
Labels: type: typo

#524 Add FAQ for user blocking
  guide/popular-topics/faq.md
Labels: t: page/section addition, type: enhancement

#532 fix: force viewport and charset meta tags
  guide/.vuepress/config.js
Labels: type: bugfix

#538 Update README.md
  guide/sequelize/README.md
Labels: type: bugfix
