Repository discordjs/guide, pull requests merged in 2020-07, with the labels that each got.

#425 fix(reactions): fix presence intent name
  guide/popular-topics/reactions.md
Labels: bug fix

#431 fix(additional-info/changes-in-v12): correct class names
  guide/additional-info/changes-in-v12.md
Labels: bug fix

#433 Add missing new VoiceConnection accessing
  guide/additional-info/changes-in-v12.md
Labels: enhancement

#435 Update Sequelize currency system guide
  guide/sequelize/currency.md
Labels: spelling/grammar

#415 replace 'multipart/form-data' with 'application/x-www-form-urlencoded'
  code-samples/oauth/simple-oauth-webserver/index.js
  guide/oauth2/README.md
Labels: bug fix

#441 Corrected misleading information
  guide/popular-topics/intents.md
Labels: bug fix
