Repository discordjs/guide, pull requests merged in 2020-04, with the labels that each got.

#363 feat: keyv guide resulting code
  code-samples/keyv/config.json
  code-samples/keyv/index.js
  guide/keyv/README.md
Labels: enhancement

#367 Remove descriptions no longer need
  guide/additional-info/changes-in-v12.md
Labels: enhancement

#369 chore: fix md formatting in update guide
  guide/additional-info/changes-in-v12.md
Labels: enhancement

#370 fix: ignore DM in audit log example
  guide/popular-topics/audit-logs.md
Labels: bug fix

#375 fix(v12-changes): permission related updated
  guide/additional-info/changes-in-v12.md
Labels: bug fix, enhancement

#372 Update common-questions.md
  guide/popular-topics/common-questions.md
Labels: bug fix

#378 fix: move success message into try block
  code-samples/command-handling/adding-features/11/commands/reload.js
  code-samples/command-handling/adding-features/12/commands/reload.js
  guide/command-handling/adding-features.md
Labels: bug fix

#354 feat: Gateway Intents article
  guide/popular-topics/intents.md
Labels: page/section addition

#356 Add information about intents
  guide/additional-info/changes-in-v12.md
Labels: enhancement

#379 fix: add intents to sidebar and apply structural changes
  guide/.vuepress/sidebar.js
  guide/popular-topics/intents.md
Labels: bug fix

#384 chore: Minor tweaks
  guide/additional-info/changes-in-v12.md
Labels: bug fix, spelling/grammar

#386 chore: fix typo in the intents guide
  guide/popular-topics/intents.md
Labels: spelling/grammar

#382 fix: arguments for ReactionCollector collect handler
  guide/popular-topics/collectors.md
Labels: branching, bug fix

#391 Switch parameters for usage of GuildEmoji constructor
  guide/sharding/extended.md
Labels: bug fix

#388 refactor(Sharding): move --trace-warnings to execArgv in additional-information
  guide/sharding/additional-information.md
Labels: bug fix

#385 fix: port documentation links to stable
  guide/command-handling/adding-features.md
  guide/commando/permissions.md
  guide/creating-your-bot/adding-more-commands.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/popular-topics/collectors.md
  guide/popular-topics/embeds.md
  guide/popular-topics/errors.md
  guide/popular-topics/permissions.md
  guide/popular-topics/reactions.md
  guide/popular-topics/webhooks.md
  guide/sharding/README.md
  guide/sharding/additional-information.md
Labels: bug fix

#389 Removed escape characters showing in Markdown
  guide/additional-info/changes-in-v12.md
Labels: spelling/grammar
