Repository discordjs/guide, pull requests merged in 2021-03, with the labels that each got.

#618 fix(styles): add missing spaces and links in tip elements
  .vscode/guide.code-snippets
  guide/additional-info/changes-in-v12.md
  guide/command-handling/adding-features.md
  guide/miscellaneous/useful-packages.md
  guide/popular-topics/faq.md
  guide/popular-topics/intents.md
  guide/popular-topics/partials.md
  guide/popular-topics/reactions.md
  guide/preparations/setting-up-a-bot-application.md
  guide/sharding/README.md
Labels: type: spelling/grammar

#616 feat(command-handling): Make cooldowns a property of client
  code-samples/command-handling/adding-features/11/index.js
  code-samples/command-handling/adding-features/12/index.js
  guide/command-handling/adding-features.md
Labels: type: enhancement

#625 docs(Commando): Update installation instructions
  guide/commando/README.md
Labels: meta: commando, type: bugfix

#539 style(*): grammar, spelling, punctuation
  guide/README.md
  guide/additional-info/async-await.md
  guide/additional-info/changes-in-v12.md
  guide/additional-info/collections.md
  guide/additional-info/es6-syntax.md
  guide/additional-info/notation.md
  guide/additional-info/rest-api.md
  guide/command-handling/README.md
  guide/command-handling/adding-features.md
  guide/command-handling/dynamic-commands.md
  guide/commando/README.md
  guide/commando/args.md
  guide/commando/client-values.md
  guide/commando/first-command.md
  guide/commando/guild-only.md
  guide/commando/permissions.md
  guide/commando/throttling.md
  guide/commando/unknown-command-response.md
  guide/commando/validators.md
  guide/creating-your-bot/README.md
  guide/creating-your-bot/adding-more-commands.md
  guide/creating-your-bot/commands-with-user-input.md
  guide/creating-your-bot/configuration-files.md
  guide/event-handling/README.md
  guide/improving-dev-environment/package-json-scripts.md
  guide/improving-dev-environment/pm2.md
  guide/keyv/README.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/miscellaneous/useful-packages.md
  guide/oauth2/README.md
  guide/popular-topics/audit-logs.md
  guide/popular-topics/canvas.md
  guide/popular-topics/collectors.md
  guide/popular-topics/embeds.md
  guide/popular-topics/errors.md
  guide/popular-topics/faq.md
  guide/popular-topics/intents.md
  guide/popular-topics/partials.md
  guide/popular-topics/permissions-extended.md
  guide/popular-topics/permissions.md
  guide/popular-topics/reactions.md
  guide/popular-topics/webhooks.md
  guide/preparations/README.md
  guide/preparations/adding-your-bot-to-servers.md
  guide/preparations/setting-up-a-bot-application.md
  guide/preparations/setting-up-a-linter.md
  guide/sequelize/README.md
  guide/sequelize/currency.md
  guide/sharding/README.md
  guide/sharding/additional-information.md
  guide/sharding/extended.md
  guide/voice/README.md
  guide/voice/optimisation-and-troubleshooting.md
  guide/voice/receiving-audio.md
  guide/voice/the-basics.md
  guide/voice/understanding-voice.md
  guide/voice/voice-broadcasts.md
Labels: type: spelling/grammar
