Repository discordjs/guide, pull requests merged in 2021-05, with the labels that each got.

#649 Fixed install instructions
  guide/commando/README.md
Labels: meta: commando, type: bugfix

#644 refactor(*): Use codeblock line highlights
  CONTRIBUTING.md
  code-samples/popular-topics/canvas/11/index.js
  code-samples/popular-topics/canvas/12/index.js
  guide/additional-info/async-await.md
  guide/additional-info/es6-syntax.md
  guide/additional-info/rest-api.md
  guide/command-handling/README.md
  guide/command-handling/adding-features.md
  guide/command-handling/dynamic-commands.md
  guide/commando/README.md
  guide/commando/args.md
  guide/commando/first-command.md
  guide/commando/guild-only.md
  guide/commando/permissions.md
  guide/commando/throttling.md
  guide/commando/unknown-command-response.md
  guide/commando/validators.md
  guide/creating-your-bot/README.md
  guide/creating-your-bot/adding-more-commands.md
  guide/creating-your-bot/commands-with-user-input.md
  guide/event-handling/README.md
  guide/keyv/README.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/oauth2/README.md
  guide/popular-topics/audit-logs.md
  guide/popular-topics/canvas.md
  guide/popular-topics/partials.md
  guide/popular-topics/reactions.md
  guide/preparations/setting-up-a-linter.md
  guide/sharding/README.md
  guide/sharding/extended.md
Labels: type: enhancement

#642 refactor(*): Utilize the DocsLink component
  guide/.vuepress/components/DocsLink.vue
  guide/command-handling/README.md
  guide/command-handling/adding-features.md
  guide/commando/permissions.md
  guide/creating-your-bot/adding-more-commands.md
  guide/event-handling/README.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/popular-topics/audit-logs.md
  guide/popular-topics/collectors.md
  guide/popular-topics/embeds.md
  guide/popular-topics/intents.md
  guide/popular-topics/permissions.md
  guide/popular-topics/reactions.md
  guide/popular-topics/webhooks.md
  guide/sharding/README.md
  guide/sharding/additional-information.md
  guide/sharding/extended.md
Labels: type: enhancement

#661 fix(*): "We"/"our"/etc. to "you"/"your"/etc.
  guide/additional-info/async-await.md
  guide/additional-info/es6-syntax.md
  guide/additional-info/rest-api.md
  guide/commando/first-command.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/miscellaneous/useful-packages.md
  guide/popular-topics/audit-logs.md
  guide/popular-topics/collectors.md
  guide/popular-topics/errors.md
  guide/popular-topics/faq.md
  guide/popular-topics/reactions.md
  guide/sequelize/README.md
  guide/sequelize/currency.md
  guide/sharding/README.md
  guide/sharding/extended.md
  guide/voice/optimisation-and-troubleshooting.md
  guide/voice/the-basics.md
  guide/voice/understanding-voice.md
Labels: type: spelling/grammar

#660 refactor(command-handling): Merge command executing page into command handling page
  code-samples/command-handling/dynamic-commands/11/commands/args-info.js
  code-samples/command-handling/dynamic-commands/11/commands/avatar.js
  code-samples/command-handling/dynamic-commands/11/commands/beep.js
  code-samples/command-handling/dynamic-commands/11/commands/kick.js
  code-samples/command-handling/dynamic-commands/11/commands/ping.js
  code-samples/command-handling/dynamic-commands/11/commands/prune.js
  code-samples/command-handling/dynamic-commands/11/commands/server.js
  code-samples/command-handling/dynamic-commands/11/commands/user-info.js
  code-samples/command-handling/dynamic-commands/11/config.json
  code-samples/command-handling/dynamic-commands/11/index.js
  code-samples/command-handling/dynamic-commands/12/commands/args-info.js
  code-samples/command-handling/dynamic-commands/12/commands/avatar.js
  code-samples/command-handling/dynamic-commands/12/commands/beep.js
  code-samples/command-handling/dynamic-commands/12/commands/kick.js
  code-samples/command-handling/dynamic-commands/12/commands/ping.js
  code-samples/command-handling/dynamic-commands/12/commands/prune.js
  code-samples/command-handling/dynamic-commands/12/commands/server.js
  code-samples/command-handling/dynamic-commands/12/commands/user-info.js
  code-samples/command-handling/dynamic-commands/12/config.json
  code-samples/command-handling/dynamic-commands/12/index.js
  code-samples/command-handling/file-setup/11/index.js
  code-samples/command-handling/file-setup/12/index.js
  guide/.vuepress/sidebar.js
  guide/command-handling/README.md
  guide/command-handling/adding-features.md
  guide/command-handling/dynamic-commands.md
Labels: type: enhancement

#666 refactor(oauth2): Update images, headers, and grammar
  code-samples/oauth/simple-oauth-webserver/index.html
  guide/oauth2/README.md
  guide/oauth2/images/add-redirects.png
  guide/oauth2/images/authorize-app-page.png
  guide/oauth2/images/create-app-page.png
  guide/oauth2/images/generate-url.png
  guide/oauth2/images/oauth2-app-page.png
Labels: type: enhancement
