Repository discordjs/guide, pull requests merged in 2021-01, with the labels that each got.

#563 use permissions of command author rather than of the bot
  guide/command-handling/adding-features.md
Labels: type: bugfix

#556 feat(preparations): token security and env vars
  guide/preparations/setting-up-a-bot-application.md
Labels: t: page/section addition

#571 feat(Intents): replace Intents placeholder
  guide/popular-topics/intents.md
Labels: reason: Discord, type: enhancement

#569 feat(adding-features): increase verbosity of cooldown section
  guide/command-handling/adding-features.md
Labels: type: enhancement
