Repository discordjs/guide, pull requests merged in 2021-07, with the labels that each got.

#690 Update embeds.md
  guide/popular-topics/embeds.md
Labels: reason: Discord, type: enhancement

#691 refactor(intents): more explicit on how to read ddev docs
  guide/popular-topics/intents.md
Labels: type: enhancement

#638 feat: interactions and slash commands
  guide/.vuepress/sidebar.ts
  guide/interactions/registering-slash-commands.md
  guide/interactions/replying-to-slash-commands.md
  guide/interactions/slash-command-permissions.md
Labels: t: page/section addition

#689 Suggestion: Eslint Rules
  guide/preparations/setting-up-a-linter.md
Labels: type: enhancement

#683 refactor(Commandhandling): rewrite command handling pages to be based upon interactions
  code-samples/command-handling/file-setup/13/commands/avatar.js
  code-samples/command-handling/file-setup/13/commands/beep.js
  code-samples/command-handling/file-setup/13/commands/kick.js
  code-samples/command-handling/file-setup/13/commands/options-info.js
  code-samples/command-handling/file-setup/13/commands/ping.js
  code-samples/command-handling/file-setup/13/commands/prune.js
  code-samples/command-handling/file-setup/13/commands/server.js
  code-samples/command-handling/file-setup/13/commands/user-info.js
  code-samples/command-handling/file-setup/13/config.json
  code-samples/command-handling/file-setup/13/index.js
  guide/.vuepress/sidebar.ts
  guide/command-handling/README.md
  guide/command-handling/adding-features.md
  guide/creating-your-bot/README.md
  guide/creating-your-bot/adding-more-commands.md
  guide/creating-your-bot/commands-with-user-input.md
  guide/creating-your-bot/configuration-files.md
Labels: type: enhancement

#693 feat: v13 collectors
  guide/popular-topics/collectors.md
Labels: type: version update

#674 feat: message components
  guide/.vuepress/sidebar.ts
  guide/interactions/buttons.md
  guide/interactions/images/select.png
  guide/interactions/images/selectephem.png
  guide/interactions/select-menus.md
Labels: t: page/section addition

#692 feat: threads
  guide/.vuepress/sidebar.ts
  guide/popular-topics/threads.md
Labels: t: page/section addition

#713 fix(CommandHandling): small typo at code block
  guide/command-handling/README.md
Labels: type: spelling/grammar

#705 feat: v13 `Permissions`.
  code-samples/popular-topics/permissions/13/index.js
  guide/popular-topics/permissions-extended.md
  guide/popular-topics/permissions.md
Labels: type: version update

#700 feat: v13 `Webhooks`.
  code-samples/popular-topics/webhooks/13/using-Webhook.js
  code-samples/popular-topics/webhooks/13/using-WebhookClient.js
  guide/popular-topics/webhooks.md
Labels: type: version update

#715 feat: update useful packages guide for v13
  guide/miscellaneous/useful-packages.md
Labels: type: version update

#714 refactor(EventHandling): use interactions
  code-samples/event-handling/file-setup/13/config.json
  code-samples/event-handling/file-setup/13/events/interactionCreate.js
  code-samples/event-handling/file-setup/13/events/ready.js
  code-samples/event-handling/file-setup/13/index.js
  code-samples/event-handling/file-setup/events/message.js
  guide/event-handling/README.md
Labels: type: version update

#717 feat(theme): Enhance theme layout and functionality
  guide/.vuepress/styles/custom-blocks.scss
  guide/.vuepress/styles/home.scss
  guide/.vuepress/styles/index.scss
  guide/.vuepress/styles/layout.scss
  guide/.vuepress/styles/navbar.scss
  guide/.vuepress/styles/palette.scss
  guide/.vuepress/styles/search.scss
  guide/.vuepress/styles/sidebar.scss
  guide/.vuepress/styles/theme-variables.scss
  guide/.vuepress/templates/index.dev.html
  guide/.vuepress/templates/index.ssr.html
  guide/.vuepress/theme/components/Navbar.vue
  guide/.vuepress/theme/components/Sidebar.vue
  guide/.vuepress/theme/components/ThemeOptions.vue
  guide/.vuepress/theme/components/ToggleDarkModeButton.vue
  guide/.vuepress/theme/components/UserSettings.vue
  guide/.vuepress/theme/components/icons/ChevronDown.vue
  guide/.vuepress/theme/components/icons/ChevronRight.vue
  guide/.vuepress/theme/composables/useColorTheme.ts
  guide/.vuepress/theme/composables/useDarkMode.ts
  guide/.vuepress/theme/layouts/Layout.vue
Labels: type: enhancement

#595 feat: voice rewrite guide
  guide/.vuepress/config.ts
  guide/.vuepress/sidebar.ts
  guide/voice/README.md
  guide/voice/audio-player.md
  guide/voice/audio-resources.md
  guide/voice/life-cycles.md
  guide/voice/optimisation-and-troubleshooting.md
  guide/voice/receiving-audio.md
  guide/voice/the-basics.md
  guide/voice/understanding-voice.md
  guide/voice/voice-broadcasts.md
  guide/voice/voice-connections.md
Labels: reason: Discord.js, type: enhancement

#694 feat: v13 embeds
  guide/popular-topics/embeds.md
Labels: type: version update

#729 feat: v13 `Reactions`.
  code-samples/popular-topics/reactions/13/awaiting-reactions.js
  code-samples/popular-topics/reactions/13/basic-reacting.js
  code-samples/popular-topics/reactions/13/uncached-messages.js
  guide/popular-topics/reactions.md
Labels: type: version update

#720 feat: v13 `FAQ`.
  guide/popular-topics/faq.md
Labels: type: version update

#731 feat(theme): Add Notifications components
  guide/.vuepress/theme/components/Notification.vue
  guide/.vuepress/theme/components/Notifications.vue
  guide/.vuepress/theme/components/icons/Close.vue
  guide/.vuepress/theme/components/icons/PartyPopper.vue
  guide/.vuepress/theme/layouts/Layout.vue
Labels: type: enhancement

#737 fix typo
  guide/creating-your-bot/adding-more-commands.md
Labels: type: spelling/grammar

#708 feat: v13 - Other/Miscallaneous changes.
  CONTRIBUTING.md
  code-samples/popular-topics/reactions/13/awaiting-reactions.js
  guide/.vuepress/theme/components/icons/ChevronDown.vue
  guide/additional-info/async-await.md
  guide/additional-info/es6-syntax.md
  guide/additional-info/notation.md
  guide/additional-info/rest-api.md
  guide/keyv/README.md
  guide/miscellaneous/parsing-mention-arguments.md
  guide/popular-topics/canvas.md
  guide/popular-topics/embeds.md
  guide/popular-topics/errors.md
  guide/popular-topics/faq.md
  guide/popular-topics/reactions.md
  guide/sequelize/README.md
  guide/sequelize/currency.md
  guide/sharding/README.md
  guide/sharding/extended.md
Labels: type: version update

#721 feat: v13 `Code Samples`.
  code-samples/additional-info/rest-api/13/index.js
  code-samples/command-handling/adding-features/12/commands/fun/beep.js
  code-samples/command-handling/adding-features/12/commands/fun/ping.js
  code-samples/command-handling/adding-features/12/commands/moderation/kick.js
  code-samples/command-handling/adding-features/12/commands/moderation/prune.js
  code-samples/command-handling/adding-features/12/commands/utility/args-info.js
  code-samples/command-handling/adding-features/12/commands/utility/avatar.js
  code-samples/command-handling/adding-features/12/commands/utility/help.js
  code-samples/command-handling/adding-features/12/commands/utility/reload.js
  code-samples/command-handling/adding-features/12/commands/utility/server.js
  code-samples/command-handling/adding-features/12/commands/utility/user-info.js
  code-samples/command-handling/adding-features/12/index.js
  code-samples/command-handling/file-setup/12/commands/args-info.js
  code-samples/command-handling/file-setup/12/commands/avatar.js
  code-samples/command-handling/file-setup/12/commands/beep.js
  code-samples/command-handling/file-setup/12/commands/kick.js
  code-samples/command-handling/file-setup/12/commands/ping.js
  code-samples/command-handling/file-setup/12/commands/prune.js
  code-samples/command-handling/file-setup/12/commands/server.js
  code-samples/command-handling/file-setup/12/commands/user-info.js
  code-samples/command-handling/file-setup/12/config.json
  code-samples/command-handling/file-setup/12/index.js
  code-samples/command-handling/file-setup/13/commands/user-info.js
  code-samples/command-handling/file-setup/13/index.js
  code-samples/creating-your-bot/adding-more-commands/config.json
  code-samples/creating-your-bot/adding-more-commands/index.js
  code-samples/creating-your-bot/commands-with-user-input/12/config.json
  code-samples/creating-your-bot/commands-with-user-input/12/index.js
  code-samples/creating-your-bot/configuration-files/config.json
  code-samples/creating-your-bot/configuration-files/index.js
  code-samples/creating-your-bot/up-and-running/index.js
  code-samples/event-handling/file-setup/13/index.js
  code-samples/keyv/config.json
  code-samples/keyv/index.js
  code-samples/miscellaneous/parsing-mention-arguments/12/config.json
  code-samples/miscellaneous/parsing-mention-arguments/13/config.json
  code-samples/miscellaneous/parsing-mention-arguments/13/index.js
  code-samples/popular-topics/canvas/13/index.js
  code-samples/popular-topics/canvas/13/wallpaper.jpg
  code-samples/popular-topics/permissions/13/index.js
  code-samples/sequelize/currency/13/app.js
  code-samples/sequelize/currency/13/dbInit.js
  code-samples/sequelize/currency/13/dbObjects.js
  code-samples/sequelize/currency/13/models/CurrencyShop.js
  code-samples/sequelize/currency/13/models/UserItems.js
  code-samples/sequelize/currency/13/models/Users.js
  code-samples/sequelize/tags/sequelize.js
  guide/additional-info/rest-api.md
  guide/command-handling/README.md
  guide/creating-your-bot/README.md
  guide/creating-your-bot/adding-more-commands.md
  guide/event-handling/README.md
  guide/keyv/README.md
  guide/popular-topics/canvas.md
  guide/sequelize/README.md
  guide/sequelize/currency.md
Labels: type: version update

#738 fix(interactions): Use subcommand (group) casing
  guide/interactions/registering-slash-commands.md
Labels: type: spelling/grammar

#739 fix(collectors): typo in awaitMessageComponent
  guide/popular-topics/collectors.md
Labels: type: spelling/grammar

#734 fix(interactions): use cmd opt resolver & add missing option type
  code-samples/command-handling/file-setup/13/commands/avatar.js
  code-samples/command-handling/file-setup/13/commands/kick.js
  code-samples/command-handling/file-setup/13/commands/options-info.js
  code-samples/command-handling/file-setup/13/commands/prune.js
  guide/interactions/registering-slash-commands.md
  guide/interactions/replying-to-slash-commands.md
Labels: reason: Discord.js, type: version update

#735 feat(interactions): advanced deployment
  guide/interactions/registering-slash-commands.md
Labels: t: page/section addition
