Repository discordjs/guide, pull requests merged in 2021-08, with the labels that each got.

#741 feat(Webhooks): use new webhook constructor syntax
  code-samples/popular-topics/webhooks/13/using-WebhookClient.js
  guide/popular-topics/webhooks.md
Labels: type: enhancement

#680 feat: v13 changes guide
  guide/.vuepress/sidebar.ts
  guide/additional-info/changes-in-v13.md
Labels: reason: Discord.js, t: page/section addition, type: enhancement

#755 fix: typo in "Advanced deployment" example
  guide/interactions/registering-slash-commands.md
Labels: type: spelling/grammar

#758 feat: Add tip for global commands.
  guide/interactions/slash-command-permissions.md
Labels: t: page/section addition

#767 fix: consistency in Sequelize delta section
  guide/sequelize/README.md
Labels: type: spelling/grammar

#771 fix(*): bump the required Node.js version
  guide/additional-info/changes-in-v13.md
  guide/preparations/README.md
Labels: reason: Discord.js, type: version update

#746 feat: more v13 changes
  guide/additional-info/changes-in-v13.md
Labels: type: version update

#775 fix: Typo
  guide/additional-info/changes-in-v13.md
Labels: type: spelling/grammar

#774 player.* and AudioPlayerStatus.* instead of connection.* and VoiceConnectionStatus.*
  guide/voice/audio-player.md
Labels: type: bugfix

#777 fix(Interactions): rename last remaining defer to deferReply
  guide/interactions/replying-to-slash-commands.md
Labels: reason: Discord.js, type: version update

#773 feat(v13-changes): Channel#isVoice() in v13 additions
  guide/additional-info/changes-in-v13.md
Labels: reason: Discord.js, type: version update

#779 fix(v13-changes): LimitedInteraction constructor
  guide/additional-info/changes-in-v13.md
Labels: type: bugfix

#780 workflows(Test): upgrade Node version to 16.x
  .github/workflows/test.yml
Labels: meta: dependencies, type: version update

#765 feat(Interactions): add subcommand parsing section
  guide/interactions/replying-to-slash-commands.md
Labels: t: page/section addition

#790 feat: list of changed id properties
  guide/additional-info/changes-in-v13.md
Labels: t: page/section addition

#792 Changing a method on the example
  guide/interactions/slash-command-permissions.md
Labels: type: bugfix

#791 fix(FAQ): update setPresence syntax sample
  guide/popular-topics/faq.md
Labels: type: version update

#768 fix(sequelize): data type of `item_id`
  code-samples/sequelize/currency/13/models/UserItems.js
  guide/sequelize/currency.md
Labels: type: bugfix

#763 refactor: Partially Rewrite Canvas Page
  code-samples/popular-topics/canvas/13/index.js
  guide/popular-topics/canvas.md
  guide/popular-topics/images/canvas-add-name.png
  guide/popular-topics/images/canvas-after-text-wrap.png
  guide/popular-topics/images/canvas-before-text-wrap.png
  guide/popular-topics/images/canvas-circle-avatar.png
  guide/popular-topics/images/canvas-final-result.png
  guide/popular-topics/images/canvas-square-avatar.png
  guide/popular-topics/images/canvas-stretched-avatar.png
Labels: type: enhancement

#766 feat(Builders): add builders page to popular-topics
  guide/.vuepress/sidebar.ts
  guide/popular-topics/builders.md
Labels: t: page/section addition

#786 refactor: refactor command deployment & command handling
  code-samples/command-handling/file-setup/13/commands/avatar.js
  code-samples/command-handling/file-setup/13/commands/beep.js
  code-samples/command-handling/file-setup/13/commands/kick.js
  code-samples/command-handling/file-setup/13/commands/options-info.js
  code-samples/command-handling/file-setup/13/commands/ping.js
  code-samples/command-handling/file-setup/13/commands/prune.js
  code-samples/command-handling/file-setup/13/commands/server.js
  code-samples/command-handling/file-setup/13/commands/user-info.js
  guide/command-handling/README.md
  guide/interactions/registering-slash-commands.md
  guide/interactions/slash-command-permissions.md
Labels: type: enhancement

#796 fix(Interactions): update outdated link to Discord developer docs
  guide/interactions/registering-slash-commands.md
Labels: type: bugfix, reason: Discord

#798 chore: Fix a typo (Discords => Discord's)
  guide/popular-topics/permissions-extended.md
Labels: type: spelling/grammar

#805 refactor(Interactions): use builders in options parsing
  guide/interactions/replying-to-slash-commands.md
Labels: type: enhancement

#800 feat: Make command destructuring consistent.
  code-samples/additional-info/rest-api/13/index.js
  code-samples/command-handling/file-setup/13/index.js
  code-samples/creating-your-bot/adding-more-commands/index.js
  code-samples/popular-topics/permissions/13/index.js
  code-samples/popular-topics/reactions/13/basic-reacting.js
  code-samples/sequelize/currency/13/app.js
  code-samples/sequelize/tags/sequelize.js
  code-samples/sharding/extended/13/bot.js
  code-samples/sharding/getting-started/13/bot.js
  guide/additional-info/async-await.md
  guide/additional-info/es6-syntax.md
  guide/additional-info/rest-api.md
  guide/command-handling/README.md
  guide/creating-your-bot/adding-more-commands.md
  guide/interactions/replying-to-slash-commands.md
  guide/popular-topics/reactions.md
  guide/sequelize/README.md
  guide/sequelize/currency.md
  guide/sharding/README.md
  guide/sharding/extended.md
Labels: type: enhancement

#807 Fix: Update the invite link structure and explanation
  guide/preparations/adding-your-bot-to-servers.md
Labels: type: enhancement

#809 Add explicit variable definitions for client and guild id
  guide/interactions/registering-slash-commands.md
Labels: type: enhancement

#816 Fix typo
  guide/interactions/registering-slash-commands.md
Labels: type: spelling/grammar

#815 refactor(preparations): improve instructions for installing node and djs
  guide/preparations/README.md
Labels: type: enhancement

#818 fix: Update `guildBanAdd` parameters to version 13
  guide/popular-topics/audit-logs.md
Labels: type: version update

#824 Update Ping Example
  guide/popular-topics/faq.md
Labels: type: version update

#769 fix: Change interaction handler sample code
  guide/command-handling/README.md
Labels: type: enhancement

#819 refactor(preparations): Rewrite `/preparations/` pages
  guide/preparations/README.md
  guide/preparations/adding-your-bot-to-servers.md
  guide/preparations/setting-up-a-bot-application.md
  guide/preparations/setting-up-a-linter.md
Labels: type: enhancement, type: spelling/grammar

#826 refactor(creating-your-bot): Rewrite `/creating-your-bot/` pages
  README.md
  code-samples/command-handling/file-setup/13/config.json
  code-samples/creating-your-bot/command-handling/commands/avatar.js
  code-samples/creating-your-bot/command-handling/commands/beep.js
  code-samples/creating-your-bot/command-handling/commands/kick.js
  code-samples/creating-your-bot/command-handling/commands/options-info.js
  code-samples/creating-your-bot/command-handling/commands/ping.js
  code-samples/creating-your-bot/command-handling/commands/prune.js
  code-samples/creating-your-bot/command-handling/commands/server.js
  code-samples/creating-your-bot/command-handling/commands/user-info.js
  code-samples/creating-your-bot/command-handling/config.json
  code-samples/creating-your-bot/command-handling/deploy-commands.js
  code-samples/creating-your-bot/command-handling/index.js
  code-samples/creating-your-bot/configuration-files/index.js
  code-samples/creating-your-bot/creating-commands/config.json
  code-samples/creating-your-bot/creating-commands/deploy-commands.js
  code-samples/creating-your-bot/creating-commands/index.js
  code-samples/creating-your-bot/event-handling/config.json
  code-samples/creating-your-bot/event-handling/events/interactionCreate.js
  code-samples/creating-your-bot/event-handling/events/ready.js
  code-samples/creating-your-bot/event-handling/index.js
  code-samples/creating-your-bot/initial-files/config.json
  code-samples/creating-your-bot/initial-files/index.js
  code-samples/event-handling/file-setup/13/config.json
  guide/.vuepress/sidebar.ts
  guide/README.md
  guide/additional-info/es6-syntax.md
  guide/command-handling/README.md
  guide/creating-your-bot/README.md
  guide/creating-your-bot/adding-more-commands.md
  guide/creating-your-bot/command-handling.md
  guide/creating-your-bot/configuration-files.md
  guide/creating-your-bot/creating-commands.md
  guide/creating-your-bot/event-handling.md
  guide/event-handling/README.md
  guide/interactions/registering-slash-commands.md
  guide/keyv/README.md
Labels: type: enhancement, type: spelling/grammar, t: page/section addition

#845 Typo: Removes extra space after codeblock
  guide/interactions/registering-slash-commands.md
Labels: type: spelling/grammar
