Repository discordjs/guide, pull requests merged in 2021-04, with the labels that each got.

#630 Add directory-creating/-switching for MacOS
  guide/preparations/README.md
Labels: type: enhancement

#634 refactor(oauth): Use express instead of native http module
  code-samples/oauth/simple-oauth-webserver/config.json
  code-samples/oauth/simple-oauth-webserver/index.html
  code-samples/oauth/simple-oauth-webserver/index.js
  guide/oauth2/README.md
Labels: type: enhancement

#645 refactor(*): Rename Tutorial Bot to Guide Bot
  guide/.vuepress/enhanceApp.js
  guide/creating-your-bot/adding-more-commands.md
  guide/creating-your-bot/commands-with-user-input.md
  guide/preparations/images/bot-auth-page.png
  guide/preparations/images/bot-in-memberlist.png
  guide/preparations/images/create-app.png
  guide/preparations/images/create-bot.png
  guide/preparations/images/created-bot.png
Labels: type: enhancement

#640 feat: add allowedMentions to faq
  guide/popular-topics/faq.md
Labels: t: page/section addition

#629 fix(sharding): sharding guide overhaul
  code-samples/sharding/extended/11/bot.js
  code-samples/sharding/extended/12/bot.js
  guide/sharding/additional-information.md
  guide/sharding/extended.md
Labels: type: bugfix

#647 fix: reloading commands via alias
  code-samples/command-handling/adding-features/11/commands/utility/reload.js
  code-samples/command-handling/adding-features/12/commands/utility/reload.js
  guide/command-handling/adding-features.md
Labels: type: bugfix
