Repository discordjs/guide, pull requests merged in 2022-06, with the labels that each got.

#943 feat(autocomplete): Add autocomplete page
  guide/.vuepress/sidebar.ts
  guide/interactions/autocomplete.md
Labels: t: page/section addition

#1128 feat: add context menu
  guide/.vuepress/sidebar.ts
  guide/interactions/context-menus.md
Labels: t: page/section addition

#1140 Update errors.md
  guide/popular-topics/errors.md
Labels: type: enhancement

#1129 Update modals.md
  guide/interactions/modals.md
Labels: t: page/section addition

#1116 feat(slashcommands): add slash command permissions section
  guide/interactions/slash-commands.md
Labels: t: page/section addition

#1152 feat(autocomplete): remove `response` variable
  guide/interactions/autocomplete.md
Labels: type: enhancement

#1155 fix(code-samples): outdated code
  code-samples/popular-topics/webhooks/13/using-Webhook.js
Labels: type: bugfix
