Repository discordjs/guide, pull requests merged in 2022-10, with the labels that each got.

#1282 fix: use `UserManager#send()` for sending a DM
  guide/popular-topics/faq.md
Labels: type: enhancement

#1287 feat(misc): add cache customization guide
  guide/.vuepress/sidebar.ts
  guide/miscellaneous/cache-customization.md
Labels: t: page/section addition

#1292 Numbers: Numerical vs written representation
  guide/popular-topics/embeds.md
Labels: type: spelling/grammar

#1293 fix invalid pnpm init command
  guide/improving-dev-environment/package-json-scripts.md
  guide/preparations/README.md
Labels: type: bugfix

#1296 Example code error with ChannelTypes.GuildText
  guide/slash-commands/advanced-creation.md
Labels: type: bugfix

#1300 feat: prefer Events enum usage
  CONTRIBUTING.md
  code-samples/additional-info/rest-api/14/index.js
  code-samples/creating-your-bot/command-deployment/index.js
  code-samples/creating-your-bot/command-handling/index.js
  code-samples/creating-your-bot/initial-files/index.js
  code-samples/creating-your-bot/slash-commands/index.js
  code-samples/keyv/index.js
  code-samples/popular-topics/canvas/14/index.js
  code-samples/popular-topics/permissions/14/index.js
  code-samples/popular-topics/reactions/14/awaiting-reactions.js
  code-samples/popular-topics/reactions/14/basic-reacting.js
  code-samples/popular-topics/reactions/14/uncached-messages.js
  code-samples/popular-topics/webhooks/14/using-Webhook.js
  code-samples/sequelize/currency/14/app.js
  code-samples/sequelize/tags/sequelize.js
  code-samples/sharding/extended/14/bot.js
  code-samples/sharding/getting-started/14/bot.js
  guide/additional-info/async-await.md
  guide/additional-info/es6-syntax.md
  guide/additional-info/rest-api.md
  guide/creating-your-bot/command-handling.md
  guide/creating-your-bot/event-handling.md
  guide/creating-your-bot/main-file.md
  guide/interactions/buttons.md
  guide/interactions/context-menus.md
  guide/interactions/modals.md
  guide/interactions/select-menus.md
  guide/keyv/README.md
  guide/miscellaneous/useful-packages.md
  guide/popular-topics/audit-logs.md
  guide/popular-topics/canvas.md
  guide/popular-topics/errors.md
  guide/popular-topics/faq.md
  guide/popular-topics/reactions.md
  guide/popular-topics/webhooks.md
  guide/sequelize/README.md
  guide/sequelize/currency.md
  guide/sharding/README.md
  guide/sharding/extended.md
  guide/slash-commands/autocomplete.md
  guide/slash-commands/response-methods.md
Labels: type: enhancement

#1299 feat: guide on parsing choices
  guide/slash-commands/parsing-options.md
Labels: t: page/section addition

#1302 fix: update typos
  guide/creating-your-bot/slash-commands.md
  guide/popular-topics/audit-logs.md
  guide/slash-commands/advanced-creation.md
Labels: type: spelling/grammar

#1301 fix: update error name
  guide/popular-topics/intents.md
Labels: type: version update

#1303 fix(Oauth2): set request body to string
  code-samples/oauth/simple-oauth-webserver/index.js
  guide/oauth2/README.md
Labels: type: bugfix

#1269 fix: use `request.body.json()`
  code-samples/additional-info/rest-api/14/index.js
  code-samples/oauth/simple-oauth-webserver/index.js
  guide/additional-info/rest-api.md
  guide/oauth2/README.md
Labels: type: enhancement

#1306 Fixed the wrong URL at Resulting Code
  guide/creating-your-bot/command-handling.md
Labels: type: bugfix

#1308 fix: update typos
  guide/miscellaneous/useful-packages.md
  guide/slash-commands/parsing-options.md
  guide/slash-commands/response-methods.md
Labels: type: spelling/grammar

#1309 feat: add bot timeout missing access
  guide/popular-topics/permissions-extended.md
Labels: type: enhancement

#1315 fix: remove incorrect warning
  guide/slash-commands/response-methods.md
Labels: reason: Discord

#1319 feat: additional notes for TypeScript users
  guide/creating-your-bot/command-handling.md
Labels: t: page/section addition

#1316 feat(faq): add member timeout
  guide/popular-topics/faq.md
Labels: t: page/section addition

#1320 feat(select-menus): add access select menu values
  guide/interactions/select-menus.md
Labels: t: page/section addition

#1295 fix(Permissions): use correct name for constructor
  guide/popular-topics/permissions.md
Labels: type: bugfix, type: version update

#1327 Correct the response for "Ephemeral responses"
  guide/slash-commands/response-methods.md
Labels: type: bugfix

#1328 Add correct link to Buttons page
  guide/slash-commands/permissions.md
Labels: type: bugfix

#1307 feat(Autocomplete): AutocompleteInteraction handling and separate command function
  guide/creating-your-bot/command-handling.md
  guide/slash-commands/autocomplete.md
Labels: type: enhancement
