Repository discordjs/guide, pull requests merged in 2022-12, with the labels that each got.

#1358 chore(commands): typo
  guide/slash-commands/advanced-creation.md
Labels: type: bugfix

#1355 Fixing the redirects to the slash command pages
  guide/interactions/context-menus.md
Labels: type: bugfix

#1361 Remove locales in support URLs
  guide/popular-topics/intents.md
  guide/popular-topics/permissions-extended.md
  guide/slash-commands/deleting-commands.md
  guide/whats-new.md
Labels: type: enhancement

#1363 fix: rename SelectMenu to StringSelectMenu
  guide/additional-info/changes-in-v14.md
  guide/interactions/modals.md
  guide/interactions/select-menus.md
Labels: type: bugfix

#1368 Fix DocsLink path for threads page
  guide/popular-topics/threads.md
Labels: type: bugfix

#1366 feat(v14-changes): mention discord-api-types in the list of re-exported modules
  guide/additional-info/changes-in-v14.md
Labels: type: enhancement

#1365 Removal of Number Intent Example
  guide/popular-topics/intents.md
Labels: type: enhancement

#1344 fix(command-handling): add import for Events
  guide/creating-your-bot/command-handling.md
Labels: type: bugfix

#1375 fix: rename SelectMenu to StringSelect
  guide/popular-topics/collectors.md
Labels: type: version update

#1382 feat(voice): Add sodium-native encryption package
  guide/voice/README.md
Labels: type: enhancement
