Repository discordjs/guide, pull requests merged in 2022-03, with the labels that each got.

#1034 feat(perm-ext): timeout member with administrator
  guide/popular-topics/permissions-extended.md
Labels: type: enhancement, reason: Discord

#1043 feat(faq): use optional chaining to access status
  guide/popular-topics/faq.md
Labels: type: bugfix

#1051 Slash commands pages in one single page
  guide/.vuepress/sidebar.ts
  guide/additional-info/changes-in-v13.md
  guide/creating-your-bot/creating-commands.md
  guide/interactions/buttons.md
  guide/interactions/registering-slash-commands.md
  guide/interactions/select-menus.md
  guide/interactions/slash-command-permissions.md
  guide/interactions/slash-commands.md
  guide/popular-topics/canvas.md
  guide/popular-topics/permissions-extended.md
  guide/whats-new.md
Labels: type: enhancement

#1015 refactor: use lowercase discord.js everywhere
  README.md
  guide/.vuepress/config.ts
  guide/creating-your-bot/creating-commands.md
Labels: type: enhancement

#951 fix(misc): make parsing mention arguments more resilient
  guide/miscellaneous/parsing-mention-arguments.md
Labels: type: enhancement

#1068 fix: typo by escaping character
  guide/sequelize/README.md
Labels: type: spelling/grammar

#1074 patch(rest-api): code block highlighting
  guide/additional-info/rest-api.md
Labels: type: spelling/grammar
