Repository discordjs/guide, pull requests merged in 2022-05, with the labels that each got.

#1077 Change button "custom_id" to "customId"
  guide/interactions/buttons.md
Labels: type: enhancement

#1083 chore: Update created bot page for reset token changes
  guide/preparations/images/created-bot.png
  guide/preparations/setting-up-a-bot-application.md
Labels: type: enhancement, reason: Discord

#1112 fix(docs): update embed limits link
  guide/popular-topics/embeds.md
Labels: type: bugfix, reason: Discord

#1086 fix: replace old interaction.reply code
  code-samples/popular-topics/reactions/13/awaiting-reactions.js
  code-samples/popular-topics/reactions/13/basic-reacting.js
  guide/popular-topics/collectors.md
Labels: type: enhancement

#1091 new privileged intent August 31, 2022** not april
  guide/whats-new.md
Labels: type: enhancement, reason: Discord.js

#1096 fix(faq): replace old link
  guide/popular-topics/faq.md
Labels: type: bugfix

#1099 refactor(faq): remove `ytdl` usage
  guide/popular-topics/faq.md
Labels: type: enhancement, reason: Discord

#1059 feat: replace 'canvas' with '@napi-rs/canvas'
  code-samples/popular-topics/canvas/13/index.js
  guide/popular-topics/canvas.md
Labels: type: enhancement

#1075 Changed babel-eslint to @babel/eslint-parser
  package-lock.json
  package.json
Labels: type: enhancement, meta: dependencies

#1094 Remove Slash Command Permissions Section
  guide/interactions/slash-commands.md
Labels: reason: Discord

#1069 feat: path construction
  code-samples/creating-your-bot/command-handling/deploy-commands.js
  code-samples/creating-your-bot/command-handling/index.js
  code-samples/creating-your-bot/event-handling/index.js
  guide/creating-your-bot/command-handling.md
  guide/creating-your-bot/event-handling.md
Labels: type: enhancement

#1060 feat: add v14 modals guide
  guide/.vuepress/sidebar.ts
  guide/interactions/images/modal-example.png
  guide/interactions/modals.md
Labels: t: page/section addition, type: version update

#1120 feat(Interactions): Add attachment option
  guide/interactions/slash-commands.md
Labels: type: enhancement, reason: Discord.js, reason: Discord

#1117 feat: add v13 modals guide (#1060)
  guide/.vuepress/sidebar.ts
  guide/interactions/images/modal-example.png
  guide/interactions/modals.md
Labels: t: page/section addition
