Repository discordjs/guide, pull requests merged in 2022-07, with the labels that each got.

#1168 Correct code group syntax in OAuth2 Page
  guide/oauth2/README.md
Labels: type: bugfix

#1169 Useless part of the code was removed
  guide/interactions/buttons.md
Labels: type: enhancement

#1161 error!
  code-samples/popular-topics/canvas/13/index.js
Labels: type: bugfix

#1158 chore(eslint): error on indentation
  .eslintrc.js
Labels: meta: github

#1170 fix(useful-packages): fix pino-pretty script example
  guide/miscellaneous/useful-packages.md
Labels: type: bugfix

#1011 feat: Add v13 -> v14 migration guide
  .gitignore
  guide/.vuepress/sidebar.ts
  guide/additional-info/changes-in-v14.md
Labels: t: page/section addition, type: version update

#1151 change 'USER' to 2
  guide/interactions/context-menus.md
Labels: type: bugfix

#1160 deleting commands guide
  guide/.vuepress/sidebar.ts
  guide/creating-your-bot/deleting-commands.md
  guide/creating-your-bot/images/bots-and-apps.png
  guide/creating-your-bot/images/commands-copy-id.png
Labels: t: page/section addition, 🍒 v13

#1178 change unsafe builders to disable/enableValidators
  guide/additional-info/changes-in-v14.md
Labels: t: page/section addition, 🍒 v13

#1180 Fix ThreadMembersUpdate typo
  guide/additional-info/changes-in-v14.md
Labels: type: bugfix, 🍒 v13

#1184 refactor: Ensure version 13 guide only installs version 13
  guide/additional-info/changes-in-v13.md
  guide/preparations/README.md
  guide/sequelize/README.md
Labels: type: version update

#1197 fix(mention-user-by-Id)
  guide/popular-topics/faq.md
Labels: type: bugfix, 🍒 v13

#1198 Mention Util change
  guide/additional-info/changes-in-v14.md
Labels: type: version update, 🍒 v13

#1204 fix(faq): $ in template literal
  guide/popular-topics/faq.md
Labels: type: bugfix, 🍒 v13

#1205 fix(additional-info): code sample
  guide/additional-info/changes-in-v14.md
Labels: type: bugfix, 🍒 v13

#1209 typo(deleting-commands): Fix typos and weird wording
  guide/creating-your-bot/deleting-commands.md
Labels: type: spelling/grammar

#1195 feat(*): apply v14 changes (#1146 follow-up)
  guide/additional-info/notation.md
  guide/popular-topics/canvas.md
  guide/popular-topics/permissions.md
  guide/popular-topics/threads.md
  guide/popular-topics/webhooks.md
  guide/preparations/README.md
  guide/sequelize/README.md
  guide/sharding/extended.md
Labels: type: version update

#1215 use correct intent
  code-samples/popular-topics/reactions/14/awaiting-reactions.js
  guide/popular-topics/reactions.md
Labels: type: bugfix

#1208 Update canvas guide to use loadImage
  guide/popular-topics/canvas.md
Labels: type: enhancement

#1218 changed spelling mistake
  guide/interactions/modals.md
Labels: type: spelling/grammar
