Repository discordjs/guide, pull requests merged in 2022-08, with the labels that each got.

#1226 fix(Embeds): Use raw embed timestamp
  guide/popular-topics/embeds.md
Labels: type: bugfix

#1232 typo(permissions): Fix Permission flag typo
  guide/popular-topics/permissions.md
Labels: type: bugfix

#1236 Add autocomplete choice limit (25) to documentation
  guide/interactions/autocomplete.md
Labels: type: enhancement

#1234 Mention `restWsBridgeTimeout` in the v14 upgrade documentation
  guide/additional-info/changes-in-v14.md
Labels: type: enhancement, 🍒 v13

#1243 change highlight lines
  guide/interactions/slash-commands.md
Labels: type: bugfix

#1212 fix(examples): Improve examples
  guide/interactions/autocomplete.md
  guide/interactions/buttons.md
  guide/interactions/context-menus.md
  guide/interactions/slash-commands.md
Labels: type: enhancement

#1250 fix(Intents): typo on intents guide
  guide/popular-topics/intents.md
Labels: type: spelling/grammar
