Repository discordjs/guide, pull requests merged in 2022-09, with the labels that each got.

#1253 Fix typo in modals.md
  guide/interactions/modals.md
Labels: type: spelling/grammar

#1256 Fix typo
  guide/interactions/modals.md
Labels: type: spelling/grammar

#1251 fix(navbar): documentation pointing to stable in v14
  guide/.vuepress/config.ts
Labels: type: bugfix

#1258 Typo fix from sibmissions to submissions
  guide/interactions/modals.md
Labels: type: spelling/grammar

#1257 Update modals.md
  guide/interactions/modals.md
Labels: type: bugfix

#1259 ModalSubmtInteraction -> ModalSubmitInteraction
  guide/interactions/modals.md
Labels: type: spelling/grammar

#1264 chore(eventhandling): add to project directory list
  guide/creating-your-bot/event-handling.md
Labels: type: enhancement

#1255 chore(Interactions): remove interaction typeguards removal
  guide/additional-info/changes-in-v14.md
  guide/interactions/autocomplete.md
  guide/interactions/modals.md
Labels: type: enhancement, type: version update

#1266 chore: Update guide to 14.3.0
  guide/additional-info/changes-in-v14.md
  guide/creating-your-bot/command-handling.md
  guide/creating-your-bot/creating-commands.md
  guide/creating-your-bot/deleting-commands.md
  guide/interactions/slash-commands.md
  guide/popular-topics/builders.md
  guide/popular-topics/threads.md
  guide/sequelize/currency.md
Labels: type: version update

#1242 chore: Mention deleteMessageSeconds instead of deleteMessageDays
  guide/additional-info/changes-in-v13.md
  guide/additional-info/changes-in-v14.md
Labels: reason: Discord, type: version update

#1265 Forum channels
  guide/additional-info/changes-in-v14.md
  guide/popular-topics/faq.md
Labels: t: page/section addition

#1272 fix: forum example
  guide/popular-topics/faq.md
Labels: type: bugfix

#1279 DocsLink use main branch as default
  guide/.vuepress/components/DocsLink.vue
Labels: type: enhancement, meta: branching
