Repository discordjs/guide, pull requests merged in 2023-12, with the labels that each got.

#1534 fix(select-menus): string select menu highlight lines
  guide/message-components/select-menus.md
Labels: type: bugfix

#1535 fix(slash-commands): clarify subfolder creation to avoid confusion
  guide/creating-your-bot/slash-commands.md
Labels: type: enhancement

#1536 fix(select-menus): Improper "it's" contraction
  guide/message-components/select-menus.md
Labels: type: spelling/grammar

#1537 fix(interactions): Improper "you're" contraction
  guide/message-components/interactions.md
Labels: type: spelling/grammar

#1540 fix(cache-customization): Access `client` from callback parameter
  guide/miscellaneous/cache-customization.md
Labels: type: bugfix

#1538 fix(sequelize): Highlight correct code change in syncing
  guide/sequelize/README.md
Labels: type: bugfix
