Repository discordjs/guide, pull requests merged in 2023-11, with the labels that each got.

#1515 fix(command-handling): use handler for command categories
  guide/creating-your-bot/command-handling.md
Labels: type: bugfix

#1521 fix(popular-topics): typo in terminology
  guide/popular-topics/permissions.md
Labels: type: spelling/grammar

#1505 Update intents.md
  guide/popular-topics/intents.md
Labels: type: enhancement

#1522 refactor(create-your-bot): bots are always created now
  guide/preparations/images/create-bot.png
  guide/preparations/images/created-bot.png
  guide/preparations/setting-up-a-bot-application.md
Labels: reason: Discord

#1523 fix: Update broken links
  guide/creating-your-bot/README.md
  guide/creating-your-bot/command-handling.md
Labels: type: bugfix

#1529 fix(es6-syntax): rearrange username and password for consistency
  guide/additional-info/es6-syntax.md
Labels: type: enhancement

#1528 refactor: Standardise `ClientReady` event
  CONTRIBUTING.md
  code-samples/additional-features/cooldowns/index.js
  code-samples/additional-info/rest-api/14/index.js
  code-samples/creating-your-bot/command-deployment/index.js
  code-samples/creating-your-bot/command-handling/index.js
  code-samples/creating-your-bot/initial-files/index.js
  code-samples/creating-your-bot/slash-commands/index.js
  code-samples/keyv/index.js
  code-samples/popular-topics/canvas/14/index.js
  code-samples/popular-topics/permissions/14/index.js
  code-samples/popular-topics/reactions/14/awaiting-reactions.js
  code-samples/popular-topics/reactions/14/basic-reacting.js
  code-samples/popular-topics/reactions/14/uncached-messages.js
  code-samples/sequelize/tags/sequelize.js
  guide/additional-info/rest-api.md
  guide/creating-your-bot/event-handling.md
  guide/creating-your-bot/main-file.md
  guide/popular-topics/canvas.md
  guide/popular-topics/reactions.md
  guide/sequelize/README.md
  guide/sequelize/currency.md
Labels: type: enhancement

#1524 fix(command-handling): Cleanup page
  code-samples/creating-your-bot/command-handling/commands/moderation/kick.js
  code-samples/creating-your-bot/command-handling/commands/moderation/prune.js
  code-samples/creating-your-bot/command-handling/commands/utility/avatar.js
  code-samples/creating-your-bot/command-handling/commands/utility/ping.js
  code-samples/creating-your-bot/command-handling/commands/utility/server.js
  code-samples/creating-your-bot/command-handling/commands/utility/user.js
  code-samples/creating-your-bot/command-handling/config.json
  code-samples/creating-your-bot/command-handling/index.js
  guide/creating-your-bot/command-handling.md
  guide/creating-your-bot/images/after-sorting.png
  guide/creating-your-bot/images/before-sorting.png
Labels: type: bugfix

#1525 fix(command-deployment): Cleanup page
  code-samples/creating-your-bot/command-deployment/commands/moderation/kick.js
  code-samples/creating-your-bot/command-deployment/commands/moderation/prune.js
  code-samples/creating-your-bot/command-deployment/commands/utility/avatar.js
  code-samples/creating-your-bot/command-deployment/commands/utility/ping.js
  code-samples/creating-your-bot/command-deployment/commands/utility/server.js
  code-samples/creating-your-bot/command-deployment/commands/utility/user.js
  code-samples/creating-your-bot/command-deployment/index.js
  guide/creating-your-bot/command-deployment.md
Labels: type: bugfix

#1526 fix(event-handling): Cleanup page
  code-samples/creating-your-bot/event-handling/commands/utility/ping.js
  code-samples/creating-your-bot/event-handling/commands/utility/server.js
  code-samples/creating-your-bot/event-handling/commands/utility/user.js
  code-samples/creating-your-bot/event-handling/config.json
  code-samples/creating-your-bot/event-handling/events/interactionCreate.js
  guide/creating-your-bot/event-handling.md
Labels: type: bugfix

#1527 fix(additional-features): Cleanup pages
  code-samples/additional-features/cooldowns/commands/moderation/kick.js
  code-samples/additional-features/cooldowns/commands/moderation/prune.js
  code-samples/additional-features/cooldowns/commands/utility/avatar.js
  code-samples/additional-features/cooldowns/commands/utility/ping.js
  code-samples/additional-features/cooldowns/commands/utility/server.js
  code-samples/additional-features/cooldowns/commands/utility/user.js
  code-samples/additional-features/cooldowns/index.js
  code-samples/additional-features/reloading-commands/commands/moderation/kick.js
  code-samples/additional-features/reloading-commands/commands/moderation/prune.js
  code-samples/additional-features/reloading-commands/commands/utility/avatar.js
  code-samples/additional-features/reloading-commands/commands/utility/ping.js
  code-samples/additional-features/reloading-commands/commands/utility/reload.js
  code-samples/additional-features/reloading-commands/commands/utility/server.js
  code-samples/additional-features/reloading-commands/commands/utility/user.js
  code-samples/additional-features/reloading-commands/index.js
  guide/additional-features/cooldowns.md
Labels: type: bugfix
