Repository discordjs/guide, pull requests merged in 2023-02, with the labels that each got.

#1337 Update Command Error Handling
  code-samples/creating-your-bot/command-deployment/index.js
  code-samples/creating-your-bot/command-handling/index.js
  guide/creating-your-bot/command-handling.md
Labels: type: enhancement

#1408 Fix context menu documentation links
  guide/interactions/context-menus.md
Labels: type: bugfix

#1348 Add more example for sweeper element.
  guide/miscellaneous/cache-customization.md
Labels: type: enhancement

#1372 Add Aforementioned Second Option to 'Handling multiple autocomplete o…
  guide/slash-commands/autocomplete.md
Labels: type: enhancement

#1398 Added missing command file names
  guide/creating-your-bot/command-handling.md
Labels: type: bugfix

#1410 Update command-deployment.md
  guide/creating-your-bot/command-deployment.md
Labels: type: enhancement

#1423 fix(executing-commands): highlight whole handler
  guide/creating-your-bot/command-handling.md
Labels: type: bugfix

#1420 feat: Update guide to discord.js 14.8.0
  guide/.vuepress/sidebar.ts
  guide/additional-info/changes-in-v14.md
  guide/popular-topics/audit-logs.md
  guide/popular-topics/formatters.md
  guide/whats-new.md
Labels: type: version update

#1426 fix(changes-in-v14): Use Diagnostics Channel
  guide/additional-info/changes-in-v14.md
Labels: type: bugfix, type: version update
