Repository discordjs/guide, pull requests merged in 2023-03, with the labels that each got.

#1429 Fix Typo
  guide/interactions/context-menus.md
Labels: type: spelling/grammar

#1424 chore(*): Update guide to 14.8.0
  guide/.vuepress/clientAppEnhance.ts
  guide/.vuepress/components/DocsLink.vue
  guide/.vuepress/components/PackageLink.vue
  guide/.vuepress/constants.ts
  guide/.vuepress/sidebar.ts
  guide/additional-info/changes-in-v14.md
  guide/popular-topics/audit-logs.md
  guide/popular-topics/formatters.md
  guide/popular-topics/permissions.md
  guide/whats-new.md
Labels: type: version update

#1433 + Line of code was edited between articles
  guide/creating-your-bot/command-handling.md
Labels: type: enhancement

#1435 feat(*): New site subpackages
  CONTRIBUTING.md
  guide/.vuepress/components/DocsLink.vue
  guide/additional-info/changes-in-v14.md
  guide/creating-your-bot/command-handling.md
  guide/creating-your-bot/slash-commands.md
  guide/interactions/context-menus.md
  guide/interactions/select-menus.md
  guide/popular-topics/reactions.md
  guide/popular-topics/webhooks.md
  guide/slash-commands/advanced-creation.md
  guide/slash-commands/autocomplete.md
  guide/slash-commands/permissions.md
Labels: type: enhancement

#1436 chore: add util section
  guide/.vuepress/components/DocsLink.vue
Labels: type: enhancement

#1437 fix(images): update sorting images
  guide/creating-your-bot/images/after-sorting.png
  guide/creating-your-bot/images/before-sorting.png
Labels: type: bugfix
