Repository discordjs/guide, pull requests merged in 2023-04, with the labels that each got.

#1442 feat(*): Update guide to 14.9.0
  guide/.vuepress/constants.ts
  guide/additional-info/changes-in-v14.md
Labels: type: version update

#1446 fix(cooldowns): command#data#name and relative timestamp fix
  code-samples/additional-features/cooldowns/index.js
  guide/additional-features/cooldowns.md
Labels: type: bugfix

#1441 refactor(commands): do not specify the version option for REST
  code-samples/creating-your-bot/command-deployment/deploy-commands.js
  guide/creating-your-bot/command-deployment.md
  guide/slash-commands/deleting-commands.md
Labels: type: enhancement

#1427 feat: further improvements to the Creating your bot section
  code-samples/creating-your-bot/command-deployment/deploy-commands.js
  code-samples/creating-your-bot/event-handling/index.js
  guide/creating-your-bot/command-deployment.md
  guide/creating-your-bot/command-handling.md
  guide/creating-your-bot/event-handling.md
  guide/creating-your-bot/slash-commands.md
  guide/slash-commands/response-methods.md
Labels: type: enhancement

#1448 Fix for theme scrollbar
  guide/.vuepress/styles/mixins/scrollbar.scss
Labels: type: bugfix

#1453 fix(command-deployment): folder pathing variable fix
  guide/creating-your-bot/command-deployment.md
Labels: type: bugfix

#1336 feat: Components rewrite
  guide/.vuepress/sidebar.ts
  guide/interactions/buttons.md
  guide/interactions/select-menus.md
  guide/message-components/action-rows.md
  guide/message-components/buttons.md
  guide/message-components/images/select.png
  guide/message-components/interactions.md
  guide/message-components/select-menus.md
Labels: type: enhancement, t: page/section addition

#1454 fix(advanced-creation): define `ChannelType` in example
  guide/slash-commands/advanced-creation.md
Labels: type: bugfix

#1455 fix(interactions): use correct interaction
  guide/message-components/interactions.md
Labels: type: bugfix

#1456 Archived Threads can be Locked.
  guide/popular-topics/threads.md
Labels: type: enhancement, reason: Discord
