Repository discordjs/guide, pull requests merged in 2024-11, with the labels that each got.

#1591 fix(updating-from-v14): "decoration" typo
  guide/additional-info/updating-from-v14.md
Labels: type: spelling/grammar

#1593 refactor(faq): Update ping section
  guide/popular-topics/faq.md
Labels: reason: Discord.js

#1594 refactor(autocomplete): Update `getFocused()` section
  guide/slash-commands/autocomplete.md
Labels: reason: discord.js

#1592 refactor: Use `MessageFlags.Ephemeral`
  code-samples/additional-features/cooldowns/index.js
  code-samples/additional-features/reloading-commands/index.js
  code-samples/creating-your-bot/command-deployment/index.js
  code-samples/creating-your-bot/command-handling/index.js
  code-samples/creating-your-bot/event-handling/events/interactionCreate.js
  guide/additional-features/cooldowns.md
  guide/creating-your-bot/command-handling.md
  guide/creating-your-bot/event-handling.md
  guide/popular-topics/collectors.md
  guide/slash-commands/response-methods.md
Labels: reason: discord.js
