Repository discordjs/guide, pull requests merged in 2024-09, with the labels that each got.

#1575 chore: Update required Node version texts
  guide/additional-info/changes-in-v14.md
  guide/preparations/README.md
Labels: reason: Discord.js

#1574 feat(popular-topics): add subtext formatter
  guide/popular-topics/formatters.md
Labels: reason: Discord.js, type: version update

#1493 feat: add bun instructions
  guide/additional-info/rest-api.md
  guide/creating-your-bot/README.md
  guide/improving-dev-environment/package-json-scripts.md
  guide/improving-dev-environment/pm2.md
  guide/keyv/README.md
  guide/miscellaneous/useful-packages.md
  guide/oauth2/README.md
  guide/popular-topics/canvas.md
  guide/preparations/README.md
  guide/preparations/setting-up-a-linter.md
  guide/sequelize/README.md
  guide/voice/README.md
Labels: t: page/section addition

#1567 fix: remove deleting commands from collection
  code-samples/additional-features/reloading-commands/commands/utility/reload.js
Labels: type: bugfix
