Repository discordjs/guide, pull requests merged in 2024-05, with the labels that each got.

#1546 refactor(popular-topics): prefer enums usage
  guide/popular-topics/faq.md
  guide/popular-topics/formatters.md
  guide/popular-topics/threads.md
Labels: type: enhancement

#1559 feat: Move discord.js documentation links to new website
  guide/.vuepress/clientAppEnhance.ts
  guide/.vuepress/components/DocsLink.vue
  guide/.vuepress/components/PackageLink.vue
  guide/.vuepress/config.ts
  guide/.vuepress/constants.ts
  guide/additional-info/changes-in-v14.md
  guide/creating-your-bot/command-handling.md
  guide/creating-your-bot/event-handling.md
  guide/interactions/context-menus.md
  guide/interactions/modals.md
  guide/message-components/action-rows.md
  guide/message-components/buttons.md
  guide/message-components/interactions.md
  guide/message-components/select-menus.md
  guide/miscellaneous/cache-customization.md
  guide/popular-topics/audit-logs.md
  guide/popular-topics/collectors.md
  guide/popular-topics/embeds.md
  guide/popular-topics/faq.md
  guide/popular-topics/formatters.md
  guide/popular-topics/permissions.md
  guide/popular-topics/reactions.md
  guide/popular-topics/threads.md
  guide/popular-topics/webhooks.md
  guide/sharding/README.md
  guide/sharding/additional-information.md
  guide/sharding/extended.md
  guide/slash-commands/autocomplete.md
  guide/slash-commands/parsing-options.md
Labels: type: enhancement

#1558 fix(popular-topics): replace deprecated `underscore` with `underline`
  guide/popular-topics/formatters.md
Labels: type: enhancement, reason: Discord.js

#1549 fix(reloading commands): Remove command deletion in code snippet
  guide/additional-features/reloading-commands.md
Labels: type: bugfix
