Repository discordjs/guide, pull requests merged in 2025-06, with the labels that each got.

#1620 Adding ComponentsV2 page (Popular Topics)
  guide/.vuepress/sidebar.ts
  guide/popular-topics/components-v2.md
  guide/popular-topics/images/container-preview.png
  guide/popular-topics/images/file-preview.png
  guide/popular-topics/images/mediagallery-preview.png
  guide/popular-topics/images/section-preview.png
  guide/popular-topics/images/separator-preview.png
  guide/popular-topics/images/textdisplay-preview.png
  guide/popular-topics/images/thumbnail-preview.png
Labels: type: enhancement, t: page/section addition

#1618 fix(command-handling): Add `MessageFlags` to base template
  guide/creating-your-bot/command-handling.md
Labels: type: bugfix

#1629 Components refactor
  guide/.vuepress/sidebar.ts
  guide/additional-info/changes-in-v13.md
  guide/creating-your-bot/command-deployment.md
  guide/interactive-components/action-rows.md
  guide/interactive-components/buttons.md
  guide/interactive-components/images/select.png
  guide/interactive-components/interactions.md
  guide/interactive-components/select-menus.md
  guide/popular-topics/display-components.md
  guide/slash-commands/permissions.md
  guide/whats-new.md
Labels: type: enhancement
